# Generated by Django 3.2.3 on 2021-06-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True,
                                      decimal_places=1,
                                      max_digits=2,
                                      null=True),
        ),
    ]
