# Generated by Django 3.2.3 on 2021-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210622_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
