# Generated by Django 3.2.3 on 2021-06-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210626_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recommend',
            new_name='recommended',
        ),
    ]
